### ISSUE TITLE
wrong URL on PI-apps

### ISSUE THREAD

**Issue by coolprofessor** [Botspot/autostar#1]
It looks like the URL for Autostar on pi apps is the one for CloudBuddy.

**Comment by Botspot** [comment]
> It looks like the URL for Autostar on pi apps is the one for CloudBuddy.

Are you using the latest version of Pi-Apps?
[The install script on Pi-Apps](https://github.com/Botspot/pi-apps/blob/master/apps/Autostar/install) does not appear to reference cloudbuddy at all.
Am I looking at the right script?

**Comment by coolprofessor** [comment]
I'm sorry I was not clear. I meant the [Hyperlink](https://github.com/Botspot/pi-apps/blob/master/apps/Autostar/website) in the description.

**Comment by Botspot** [comment]
> I'm sorry I was not clear. I meant the [Hyperlink](https://github.com/Botspot/pi-apps/blob/master/apps/Autostar/website) in the description.

I see now.
Thanks to your feedback, this has now [been fixed](https://github.com/Botspot/pi-apps/commit/9d8a054b532504614402d43fb8fc21f93cf98614).
